// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { ListTestEntriesData, ListTestEntriesResponses, TestAdminData, TestAdminResponses, AuthLoginData, AuthLoginResponses, AuthLoginErrors, AuthSignupData, AuthSignupResponses, AuthSignupErrors, AuthCreateAdminData, AuthCreateAdminResponses, AuthCreateAdminErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const listTestEntries = <ThrowOnError extends boolean = false>(options?: Options<ListTestEntriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListTestEntriesResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/test',
        ...options
    });
};

export const testAdmin = <ThrowOnError extends boolean = false>(options?: Options<TestAdminData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<TestAdminResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/test-admin',
        ...options
    });
};

export const authLogin = <ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
        responseType: 'json',
        url: '/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const authSignup = <ThrowOnError extends boolean = false>(options: Options<AuthSignupData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AuthSignupResponses, AuthSignupErrors, ThrowOnError>({
        url: '/signup',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const authCreateAdmin = <ThrowOnError extends boolean = false>(options: Options<AuthCreateAdminData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AuthCreateAdminResponses, AuthCreateAdminErrors, ThrowOnError>({
        url: '/create-admin',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};