// This file is auto-generated by @hey-api/openapi-ts

/**
 * Represents user
 */
export type User = {
    username: string;
    callby?: string | null;
    fullname?: string | null;
};

/**
 * Represents a log in request
 */
export type LoginRequest = {
    username: string;
    password: string;
    stay_logged_in: boolean;
};

/**
 * Represents a navigation link
 */
export type Link = {
    name: string;
    to: string;
};

export type TestAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test-admin';
};

export type TestAdminResponses = {
    200: string;
};

export type TestAdminResponse = TestAdminResponses[keyof TestAdminResponses];

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/login';
};

export type AuthLoginErrors = {
    default: unknown;
};

export type AuthLoginResponses = {
    200: User;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type AuthLogoutErrors = {
    default: unknown;
};

export type AuthLogoutResponses = {
    200: string;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthSignupData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/signup';
};

export type AuthSignupErrors = {
    default: unknown;
};

export type AuthSignupResponses = {
    200: unknown;
};

export type AuthCreateAdminData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/create-admin';
};

export type AuthCreateAdminErrors = {
    default: unknown;
};

export type AuthCreateAdminResponses = {
    200: unknown;
};

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type AuthMeErrors = {
    default: unknown;
};

export type AuthMeResponses = {
    200: User;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthLinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/links';
};

export type AuthLinksErrors = {
    default: unknown;
};

export type AuthLinksResponses = {
    200: Array<Link>;
};

export type AuthLinksResponse = AuthLinksResponses[keyof AuthLinksResponses];

export type AuthAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin';
};

export type AuthAdminErrors = {
    default: unknown;
};

export type AuthAdminResponses = {
    200: boolean;
};

export type AuthAdminResponse = AuthAdminResponses[keyof AuthAdminResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};