// This file is auto-generated by @hey-api/openapi-ts

export type Test = {
    id: number;
    title: string;
    body: string;
};

export type ListTestEntriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test';
};

export type ListTestEntriesResponses = {
    200: Array<Test>;
};

export type ListTestEntriesResponse = ListTestEntriesResponses[keyof ListTestEntriesResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};